# Generated by Django 4.2 on 2026-02-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text='e.g. Hero, About, Gallery', max_length=50)),
                ('key', models.CharField(help_text='e.g. hero_title, hero_bg', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human readable name for the admin UI', max_length=100)),
                ('value', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Large Text'), ('image', 'Image URL'), ('color', 'Color Code')], default='text', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Configuration',
                'verbose_name_plural': 'Website Configurations',
                'ordering': ['section', 'label'],
            },
        ),
    ]
