# Generated by Django 4.2 on 2026-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma separated amenities', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity_adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='capacity_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('ROOM', 'Standard Room'), ('TENT', 'Luxury Tent'), ('VILLA', 'Private Villa'), ('COTTAGE', 'Cottage')], default='ROOM', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
