# Generated by Django 4.2 on 2026-02-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspass',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
