# Generated by Django 4.2 on 2026-02-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0002_accesspass_is_printed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED_ADMIN', 'Approved'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100)),
                ('access_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='recreation.accesspass')),
            ],
        ),
    ]
