# Generated by Django 4.2 on 2026-02-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_booking_adults_booking_children_booking_guest_email_and_more'),
        ('recreation', '0003_passreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSRProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='passreturn',
            old_name='approved_at',
            new_name='processed_at',
        ),
        migrations.RemoveField(
            model_name='accesspass',
            name='date_valid',
        ),
        migrations.RemoveField(
            model_name='passreturn',
            name='approved_by',
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='pass_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recreation.passtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.room'),
        ),
        migrations.AlterField(
            model_name='accesspass',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='passreturn',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED_ADMIN', 'Approved by Admin'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='passtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
