# Generated by Django 4.2 on 2026-02-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Total Hors Taxe (Excl Tax)', max_digits=12)),
                ('total_ft', models.DecimalField(decimal_places=2, help_text='Total Final Tax (Incl Tax)', max_digits=12)),
                ('balance_ptd', models.DecimalField(decimal_places=2, help_text='Balance Period To Date', max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pms.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('MOMO', 'Mobile Money'), ('VISA', 'Visa'), ('OTHER', 'Other')], max_length=20)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_line', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
            ],
        ),
    ]
