# Generated by Django 4.2 on 2026-02-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_voucher_transaction_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference_location',
            field=models.CharField(blank=True, help_text='Direct room/table reference if no booking (e.g. Table T5)', max_length=100, null=True),
        ),
    ]
