# Generated by Django 4.2 on 2026-02-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_invoice_reference_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('FIXED', 'Fixed Amount ($)'), ('PERCENT', 'Percentage (%)')], max_length=10, null=True),
        ),
    ]
