# Generated by Django 4.2 on 2026-02-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_invoice_discount_amount_invoice_discount_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOMO_LONESTAR', 'Momo Lonestar'), ('MOMO_ORANGE', 'Momo Orange'), ('VISA', 'Visa'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
