# Generated by Django 4.2 on 2026-03-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryitem_category'),
        ('finance', '0005_alter_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='inventory.order'),
        ),
    ]
