# Generated by Django 4.2 on 2026-03-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_invoiceitem_related_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOMO_LONESTAR', 'Momo Lonestar'), ('MOMO_ORANGE', 'Momo Orange'), ('VISA', 'Visa'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
