# Generated by Django 4.2 on 2026-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='main_account',
            field=models.CharField(choices=[('OTHER_REVENUE', 'Other Income Revenue'), ('PURCHASES', 'Purchases'), ('EXPENSE', 'Expense'), ('ASSETS', 'Assets'), ('LIABILITY', 'Liability')], default='EXPENSE', max_length=50),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('OTHER_REV_RECEPTION', 'Other revenue reception'), ('OTHER_REV_FOOD', 'Other revenue food'), ('OTHER_REV_DRINK', 'Other revenue drink'), ('OTHER_REV_ROOM', 'Other revenue room'), ('OTHER_REV_BOUTIQUE', 'Other revenue boutique'), ('OTHER_REV_PACKAGE', 'Other revenue package/event'), ('PURCHASE_FOOD', 'Local purchases food'), ('PURCHASE_DRINKS', 'Local purchases drinks'), ('PURCHASE_BOUTIQUE', 'Local purchases boutique'), ('PURCHASE_OTHER', 'Local purchases Other'), ('MARKETING', 'Marketing'), ('SELLING_EXPENSES', 'Selling expenses'), ('COMMISSION', 'Commission'), ('EMPLOYEE_BENEFITS', 'Employee benefits programs/nasscor'), ('FREIGHT', 'Freight'), ('INSURANCE', 'Insurance'), ('LAUNDRY_CLEANING', 'Laundry and cleaning service'), ('LEGAL_PROFESSIONAL', 'Legal and professional services'), ('POSTAGE', 'Postage'), ('REPAIRS', 'Repairs'), ('SUPPLIES_KITCHEN', 'Supplies kitchen'), ('SUPPLIES_FUEL', 'Supplies fuel generator'), ('SUPPLIES_OFFICE', 'Supply office'), ('SUPPLIES_GAS', 'Supplies gas'), ('SUPPLIES_STAFF_FOOD', 'Supplies staff food'), ('SUPPLIES_RESTAURANTS', 'Supplies restaurants'), ('SUPPLIES_ROOM', 'Supplies room'), ('SUPPLIES_OTHER', 'Supplies other'), ('TAX_WITHHOLDING', 'Taxes withholding Tax'), ('TAX_DUTY', 'Taxes duty'), ('TAX_OTHER', 'Taxes other'), ('TAX_WITHHOLDING_RENT', 'Taxes withholding on rent'), ('TAX_PAID_2_PERCENT', 'Taxes paid 2% tax'), ('TAX_WITHHELD_2_PERCENT', 'Taxes withheld 2% tax'), ('TAX_GST', 'Taxes GST'), ('TELEPHONE_INTERNET', 'Telephone / Internet'), ('TRAVEL_ENT', 'Travel & Entertainment'), ('UTILITIES', 'Utilities'), ('WAGES_DAILY', 'Wages - Daily hire'), ('WAGES_BONUS', 'Wages - bonus'), ('LOCAL_TRANS', 'Local transportation'), ('EXPENSE_MISC', 'Expenses general misc. Expense'), ('CONSTRUCTION', 'Construction'), ('RENOVATION', 'Renovation'), ('ACCOUNTS_PAYABLE', 'Accounts payable'), ('SALES_TAX_PAYABLE', 'Sales Tax Payable'), ('CASH_PAYMENT', 'Cash Payment'), ('CASH_RECEIPT', 'Cash Receipt'), ('JOURNAL', 'Journal Voucher')], max_length=50),
        ),
    ]
