# Generated by Django 4.2 on 2026-02-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_type',
            field=models.CharField(choices=[('ROOM', 'Room'), ('TABLE', 'Table'), ('BEACH', 'Beach Side'), ('POOL', 'Pool Side')], default='ROOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.CharField(blank=True, help_text='Number/ID (Room #, Table #, etc.)', max_length=50, null=True),
        ),
    ]
