# Generated by Django 4.2 on 2026-02-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_location_type_alter_order_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='preparation_station',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('BAR', 'Bar')], default='KITCHEN', max_length=20),
        ),
    ]
