# Generated by Django 4.2 on 2026-02-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_menuitem_preparation_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='stock_quantity',
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_dept', models.CharField(choices=[('MAIN', 'Main Stock'), ('POOL', 'Pool'), ('BAR', 'Bar'), ('BEACH_BAR', 'Beach Bar'), ('KITCHEN', 'Kitchen'), ('LAUNDRY', 'Laundry'), ('OFFICE', 'Office')], max_length=20)),
                ('to_dept', models.CharField(choices=[('MAIN', 'Main Stock'), ('POOL', 'Pool'), ('BAR', 'Bar'), ('BEACH_BAR', 'Beach Bar'), ('KITCHEN', 'Kitchen'), ('LAUNDRY', 'Laundry'), ('OFFICE', 'Office')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('MAIN', 'Main Stock'), ('POOL', 'Pool'), ('BAR', 'Bar'), ('BEACH_BAR', 'Beach Bar'), ('KITCHEN', 'Kitchen'), ('LAUNDRY', 'Laundry'), ('OFFICE', 'Office')], default='MAIN', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.inventoryitem')),
            ],
            options={
                'unique_together': {('item', 'department')},
            },
        ),
    ]
