# Generated by Django 4.2 on 2026-02-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_restauranttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location_type',
            field=models.CharField(choices=[('ROOM', 'Room'), ('TABLE', 'Table'), ('BEACH', 'Beach Side'), ('POOL', 'Pool Side'), ('WALK_IN', 'Walk-in')], default='ROOM', max_length=20),
        ),
    ]
