# Generated by Django 4.2 on 2026-02-26 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_order_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='inventory.inventoryitem'),
        ),
    ]
