# Generated by Django 4.2 on 2026-03-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_menuitem_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('BAR', 'Bar'), ('KITCHEN', 'Kitchen'), ('HOUSEKEEPING', 'Housekeeping'), ('OFFICE', 'Office'), ('MAINTENANCE', 'Maintenance')], default='BAR', max_length=50),
        ),
    ]
