# Generated by Django 4.2 on 2026-03-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='approver_department',
            field=models.CharField(blank=True, help_text='Department of person approving', max_length=50),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='approver_name',
            field=models.CharField(blank=True, help_text='Full name of person approving', max_length=100),
        ),
        migrations.CreateModel(
            name='OrderReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.orderitem')),
                ('order_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='inventory.orderreturn')),
            ],
        ),
    ]
